apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata: 
      labels:
        app: portal
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-04-27T10:42:24Z"
    spec:
      containers:
        - name: portal
          image: LINK_IMAGE_OF_YOUR_PORTAL_DOCKER_HUB_OR_OTHER_REGISTRY
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: portal-env-config
