apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000